//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_LEAVEv2.Supervisor {
    
    
    public partial class MyEmployeeLeaveApplications {
        
        /// <summary>
        /// GridViewWebControlSup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HR_LEAVEv2.UserControls.MainGridView GridViewWebControlSup;
    }
}
