//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Leave {
    
    
    public partial class GridViewTest {
        
        /// <summary>
        /// GridViewWebControlEmp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HR_Leave.MainGridView GridViewWebControlEmp;
        
        /// <summary>
        /// GridViewWebControlSup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HR_Leave.MainGridView GridViewWebControlSup;
        
        /// <summary>
        /// GridViewWebControlHr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HR_Leave.MainGridView GridViewWebControlHr;
    }
}
